### PR TITLE
LT-21582: Pass variant inflection features to Hermit Crab

### PR DESCRIPTION
**Pull request by JakeOliver28**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/80)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs` line 1276 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/80#-O-Mk7Vf5V5fh2kjBxCP:-O-Mk7Vf5V5fh2kjBxCQ:b2b4yi6) ([raw file](https://github.com/sillsdev/FieldWorks/blob/b095c349ecece920cc28c8e2fe81c32a191e23a6/Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs#L1276)):*
> ```Smalltalk
> 			ILexEntryRef entryRef = entry.CreateVariantEntryAndBackRef(type, TsStringUtils.MakeString("sau", Cache.DefaultVernWs));
> 			entryRef.VariantEntryTypesRS.Add(Cache.ServiceLocator.GetInstance<ILexEntryTypeRepository>().GetObject(LexEntryTypeTags.kguidLexTypFreeVar));
> #if !B4LT20889
> ```

I don't think we need to commit these conditional compilation directives do we?

**Review by JakeOliver28 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/80)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs` line 1276 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/80#-O-Mk7Vf5V5fh2kjBxCP:-O-MxB1a5BiLwb7YX96P:bqp2pez) ([raw file](https://github.com/sillsdev/FieldWorks/blob/b095c349ecece920cc28c8e2fe81c32a191e23a6/Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs#L1276)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I don't think we need to commit these conditional compilation directives do we?
</blockquote></details>

Looking at the JIRA description, I'm not really sure either way. Do you think I should remove them?

**Comment by jasonleenaylor** [comment]
*[`Src/LexText/ParserCore/HCLoader.cs` line 585 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/80#-O-NJUv27ffuU7Vf2U7u:-O-NJUv27ffuU7Vf2U7v:b-n3js69) ([raw file](https://github.com/sillsdev/FieldWorks/blob/b095c349ecece920cc28c8e2fe81c32a191e23a6/Src/LexText/ParserCore/HCLoader.cs#L585)):*
> ```Smalltalk
> 					Tuple<string, string> contexts = SplitEnvironment(env);
> 					hcAllo.Environments.Add(new AllomorphEnvironment(ConstraintType.Require, LoadEnvironmentPattern(contexts.Item1, true),
> 						LoadEnvironmentPattern(contexts.Item2, false))
> ```

Something seems funny on the indentation here.

**Comment by jasonleenaylor** [comment]
*[`Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs` line 1276 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/80#-O-Mk7Vf5V5fh2kjBxCP:-O-NJ5vM5TWSWLvj1dLI:b-3ixa9t) ([raw file](https://github.com/sillsdev/FieldWorks/blob/b095c349ecece920cc28c8e2fe81c32a191e23a6/Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs#L1276)):*
<details><summary><i>Previously, JakeOliver28 (Jake Oliver) wrote…</i></summary><blockquote>

Looking at the JIRA description, I'm not really sure either way. Do you think I should remove them?
</blockquote></details>

Unless this change was adding the B4LT20889 preprocessor directive in some file this condition will always be true. I don't see any value in keeping it.

**Review by JakeOliver28 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/80)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`Src/LexText/ParserCore/HCLoader.cs` line 585 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/80#-O-NJUv27ffuU7Vf2U7u:-O-aUQKBAxZhAIcI8VSI:bu03afn) ([raw file](https://github.com/sillsdev/FieldWorks/blob/b095c349ecece920cc28c8e2fe81c32a191e23a6/Src/LexText/ParserCore/HCLoader.cs#L585)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Something seems funny on the indentation here.
</blockquote></details>

Modified the indentation, not sure a great way to indent this code.
___
*[`Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs` line 1276 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/80#-O-Mk7Vf5V5fh2kjBxCP:-O-aUZv70akcIXMylRqz:b-j261vy) ([raw file](https://github.com/sillsdev/FieldWorks/blob/b095c349ecece920cc28c8e2fe81c32a191e23a6/Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs#L1276)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Unless this change was adding the B4LT20889 preprocessor directive in some file this condition will always be true. I don't see any value in keeping it.
</blockquote></details>

Removed the preprocessor directive

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/80#-:-O-bDd3GBDkE7UTxZX7x:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JakeOliver28)

**Pull request merged**
