### PR TITLE
Word Export LT-21768: Add Bullets and Numbering

### PR DESCRIPTION
**Pull request by mark-sil**
A remaining task is to support font properties on the bullet or number characters.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/168)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`Src/xWorks/LcmWordGenerator.cs` line 2501 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/168#-O7fJu3A7xt3RU8sQQ9n:-O7fJu3A7xt3RU8sQQ9o:b-43s630) ([raw file](https://github.com/sillsdev/FieldWorks/blob/3f67ef5b2c65b5bbfb62927a5fb3982e81c15e0c/Src/xWorks/LcmWordGenerator.cs#L2501)):*
> ```Smalltalk
> 			var abstractNum = new AbstractNum(abstractLevel) { AbstractNumberId = bulletUniqueId };
> 			var lastAbstractNum = numberingPart.Numbering.Elements<AbstractNum>().LastOrDefault();
> 			if (lastAbstractNum == null)
> ```

A comment to explain this would be good. I see that you are adding it after the last list item that is AbstractNum, or at the end. I just don't quite understand why.

**Review by jasonleenaylor — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/168#-:-O7fLBMC4S46OKdA8cuY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mark-sil)

**Comment by mark-sil** [comment]
*[`Src/xWorks/LcmWordGenerator.cs` line 2501 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/168#-O7fJu3A7xt3RU8sQQ9n:-O7icTzb8jOP6M8e9qaS:b-896fix) ([raw file](https://github.com/sillsdev/FieldWorks/blob/930073b507fdc45b44826ced36c4008bf4e71acd/Src/xWorks/LcmWordGenerator.cs#L2501)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

A comment to explain this would be good. I see that you are adding it after the last list item that is AbstractNum, or at the end. I just don't quite understand why.
</blockquote></details>

Done.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/168)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mark-sil)

**Pull request merged**
