### PR TITLE
LT-21859: Fix minor problems in parser test reports

### PR DESCRIPTION
**Pull request by jtmaxwell3**
I also fixed the problem reported by Beth.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/131)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`Src/LexText/ParserUI/ParserListener.cs` line 540 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/131#-O3ix2MVDtP_j_sZzNpo:-O3ix2MVDtP_j_sZzNpp:b8pjag4) ([raw file](https://github.com/sillsdev/FieldWorks/blob/eb4d3201db7b9885cc2afeba15477a84737a9e18/Src/LexText/ParserUI/ParserListener.cs#L540)):*
> ```Smalltalk
> 				IEnumerable<IWfiWordform> wordforms = new HashSet<IWfiWordform>();
> 				foreach (var text in m_cache.LanguageProject.InterlinearTexts)
> 					foreach (var genre in text.GenreCategories)
> ```

I feel like there is a cleaner way to do this, I'll make a suggestion tomorrow if you don't come up with one on your own.

**Comment by jtmaxwell3** [comment]
You mean LINQify it?

                                IEnumerable<IWfiWordform> wordforms = new HashSet<IWfiWordform>();
				foreach (var text in from text in m_cache.LanguageProject.InterlinearTexts
									 from genre in text.GenreCategories
									 where ContainsGenre(selectedGenre, genre)
									 select text)
					wordforms = wordforms.Union(text.UniqueWordforms());

**Review by JakeOliver28 — COMMENTED** [review]
I believe this should also work, although I'm not sure how readable this is.
```
IEnumerable<IWfiWordform> wordforms = m_cache.LanguageProject.InterlinearTexts
    .Where(text => text.GenreCategories.Any(genre => ContainsGenre(selectedGenre, genre)))
    .SelectMany(text => text.UniqueWordforms())
    .Distinct();
```

> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/131#-:-O3moRJx-XW8Gm0vP7iA:b-re07gd)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/131)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jtmaxwell3)

___
*[`Src/LexText/ParserUI/ParserListener.cs` line 540 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/131#-O3ix2MVDtP_j_sZzNpo:-O3ngKkE2X5hizBiJCjn:brann4v) ([raw file](https://github.com/sillsdev/FieldWorks/blob/eb4d3201db7b9885cc2afeba15477a84737a9e18/Src/LexText/ParserUI/ParserListener.cs#L540)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I feel like there is a cleaner way to do this, I'll make a suggestion tomorrow if you don't come up with one on your own.
</blockquote></details>

Jake was closer to what I was thinking. But I would have left the wordform collection logic out of the linq for readability.
```
foreach(var text in m_cache.LanguageProject.InterlinearTexts.Where(t => t.GenreCategories.Any(genre => ContainsGenre(selectedGenre, genre))))
{
   wordforms = wordforms.Union(text.UniqueWordforms());
}
```

Hmm. I know, let's have @aror92 pick the winner between the 4 choices.
A. Johns original nested foreach,
B. John's linqified foreach,
C. Jake's full linq solution,
D. Jason's linq foreach
___
*[`Src/LexText/ParserUI/ParserListener.cs` line 565 at r3](https://reviewable.io/reviews/sillsdev/FieldWorks/131#-O3nhi704VppLpdetu5W:-O3nhi704VppLpdetu5X:bb621s6) ([raw file](https://github.com/sillsdev/FieldWorks/blob/e2a4ca6a40f267bef08d5c56722b5dd48f9cd6d4/Src/LexText/ParserUI/ParserListener.cs#L565)):*
> ```Smalltalk
> 		}
> 
> 		private bool ContainsGenre(ICmPossibility genre1, ICmPossibility genre2)
> ```

Add a comment explaining the fact that this is here to handle the list heirarchy.

**Comment by aror92** [comment]
I find A and D the most readable options. I think I have a slight preference for A, but I'm also not very used to using linq, so that could be why.

**Comment by hahn-kev** [comment]
*[`Src/LexText/ParserUI/ParserListener.cs` line 540 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/131#-O3ix2MVDtP_j_sZzNpo:-O3oq78dBKt0qc1tp9PZ:b-4xd6yw) ([raw file](https://github.com/sillsdev/FieldWorks/blob/eb4d3201db7b9885cc2afeba15477a84737a9e18/Src/LexText/ParserUI/ParserListener.cs#L540)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Jake was closer to what I was thinking. But I would have left the wordform collection logic out of the linq for readability.
```
foreach(var text in m_cache.LanguageProject.InterlinearTexts.Where(t => t.GenreCategories.Any(genre => ContainsGenre(selectedGenre, genre))))
{
   wordforms = wordforms.Union(text.UniqueWordforms());
}
```

Hmm. I know, let's have @aror92 pick the winner between the 4 choices.
A. Johns original nested foreach,
B. John's linqified foreach,
C. Jake's full linq solution,
D. Jason's linq foreach
</blockquote></details>

Feel free to ignore me. In the current code there's the potential that `wordforms` gets unioned with the same text multiple times, now it looks like this wouldn't be a bug as union will not end up with duplicates. However it will be poor for performance. Jason's version means that each valid text is only Unioned once.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/131#-:-O3sIdYBEXhSiL6wOXpM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jtmaxwell3)

**Pull request merged**
