### PR TITLE
LT-21761: Add Table indenting and right justification

### PR DESCRIPTION
**Pull request by mark-sil**
Change-Id: I7f9835e66c6aaa5cb9039cc586683c1cb0311138

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/35)

### CODE REVIEW

**Review by aror92 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/35)* status: all files reviewed, 2 unresolved discussions (waiting on @mark-sil)

___
*[`Src/xWorks/WordStylesGenerator.cs` line 966 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/35#-NwjXjesCi9ZuXg0IqJy:-NwjXjesCi9ZuXg0IqJz:bd01mxp) ([raw file](https://github.com/sillsdev/FieldWorks/blob/84ae9121b17ef4e328a88f5d7d45aeb8daf5418d/Src/xWorks/WordStylesGenerator.cs#L966)):*
> ```Smalltalk
> 		/// <param name="tableAlignment">Returns the table alignment.</param>
> 		/// <returns>Returns the indentation value.</returns>
> 		internal static int GetTableIndentInfo(ReadOnlyPropertyTable propertyTable, ref TableRowAlignmentValues tableAlignment)
> ```

It might make more sense to place this function earlier in the code, above some of the helper functions. Perhaps right after "CalculateParagraphIndentsFromAncestors"? But this location works too if it seems better to you.
___
*[`Src/xWorks/WordStylesGenerator.cs` line 974 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/35#-NwjYnwF15Y-e72r62jo:-NwjYnwF15Y-e72r62jp:bhhflfn) ([raw file](https://github.com/sillsdev/FieldWorks/blob/84ae9121b17ef4e328a88f5d7d45aeb8daf5418d/Src/xWorks/WordStylesGenerator.cs#L974)):*
> ```Smalltalk
> 			}
> 
> 			var projectStyle = styleSheet.Styles[WordStylesGenerator.DictionaryNormal];
> ```

Do we know for sure that we'll always want to base this off DictionaryNormal? For most types of dictionary content, Configure Dictionary allows the user to change the default style used for that content, or even specify a custom one. Not sure how it works with tables, though.

**Review by mark-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/35)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @aror92)

___
*[`Src/xWorks/WordStylesGenerator.cs` line 966 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/35#-NwjXjesCi9ZuXg0IqJy:-Nwjst_s9zDVa1eFj9Vl:b-64n45k) ([raw file](https://github.com/sillsdev/FieldWorks/blob/84ae9121b17ef4e328a88f5d7d45aeb8daf5418d/Src/xWorks/WordStylesGenerator.cs#L966)):*
<details><summary><i>Previously, aror92 (Ariel Ror.) wrote…</i></summary><blockquote>

It might make more sense to place this function earlier in the code, above some of the helper functions. Perhaps right after "CalculateParagraphIndentsFromAncestors"? But this location works too if it seems better to you.
</blockquote></details>

I agree. Moved the function.
___
*[`Src/xWorks/WordStylesGenerator.cs` line 974 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/35#-NwjYnwF15Y-e72r62jo:-Nwjt-l7-kly0DnAJU6F:bp0u55i) ([raw file](https://github.com/sillsdev/FieldWorks/blob/84ae9121b17ef4e328a88f5d7d45aeb8daf5418d/Src/xWorks/WordStylesGenerator.cs#L974)):*
<details><summary><i>Previously, aror92 (Ariel Ror.) wrote…</i></summary><blockquote>

Do we know for sure that we'll always want to base this off DictionaryNormal? For most types of dictionary content, Configure Dictionary allows the user to change the default style used for that content, or even specify a custom one. Not sure how it works with tables, though.
</blockquote></details>

No, I shouldn't have used DictionaryNormal.  Now it is based on the style of the parent.

**Review by aror92 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/35)* status: all files reviewed, 1 unresolved discussion (waiting on @mark-sil)

___
*[`Src/xWorks/WordStylesGenerator.cs` line 974 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/35#-NwjYnwF15Y-e72r62jo:-NwjzRrI-PyQT0oUQLBb:b-9zoely) ([raw file](https://github.com/sillsdev/FieldWorks/blob/84ae9121b17ef4e328a88f5d7d45aeb8daf5418d/Src/xWorks/WordStylesGenerator.cs#L974)):*
<details><summary><i>Previously, mark-sil (Mark Kidder) wrote…</i></summary><blockquote>

No, I shouldn't have used DictionaryNormal.  Now it is based on the style of the parent.
</blockquote></details>

One more question: do table nodes ever have a style specified, or will config.Style just always be null for a table? If the first case, I'm thinking trying to use config.Style first and moving to config.Parent?.Style if the node doesn't have a style specified would be the way to go.

**Review by mark-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/35)* status: all files reviewed, 1 unresolved discussion (waiting on @aror92)

___
*[`Src/xWorks/WordStylesGenerator.cs` line 974 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/35#-NwjYnwF15Y-e72r62jo:-Nwk0hsf1y8IVm-4eU3s:b-kfvgwk) ([raw file](https://github.com/sillsdev/FieldWorks/blob/84ae9121b17ef4e328a88f5d7d45aeb8daf5418d/Src/xWorks/WordStylesGenerator.cs#L974)):*
<details><summary><i>Previously, aror92 (Ariel Ror.) wrote…</i></summary><blockquote>

One more question: do table nodes ever have a style specified, or will config.Style just always be null for a table? If the first case, I'm thinking trying to use config.Style first and moving to config.Parent?.Style if the node doesn't have a style specified would be the way to go.
</blockquote></details>

The table could have a style, which should apply to the content of the table.  This code is intended to make the entire table line up with the indenting used for the entry, so it should always use the parent style for indenting/justification.

**Review by aror92 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/35#-:-NwkNRKC2DqopdcgkZ8z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mark-sil)

**Pull request merged**
