### PR TITLE
Add images to word export

### PR DESCRIPTION
**Pull request by aror92**
Create image part for a word doc, create images,
clone images between document fragments,
and track relationship IDs of images.

Export caption text. Formatting of image captions
will be handled separately.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/22)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`Src/xWorks/ConfiguredLcmGenerator.cs` line 865 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/22#-NuzDUp62PhAxRWWkuIU:-NuzDUp62PhAxRWWkuIV:b-b0unl) ([raw file](https://github.com/sillsdev/FieldWorks/blob/499f1322f101f799110296d71f8799d61fbf4bd4/Src/xWorks/ConfiguredLcmGenerator.cs#L865)):*
> ```Smalltalk
> 			}
> 			return filePath;
> 			//return settings.UseRelativePaths ? filePath : new Uri(filePath).ToString();
> ```

Was this an experiment or for debugging?

**Comment by aror92** [comment]
Ah, I meant to start a conversation to ask about this here. Is there a reason we want to create a Uri in the case that we're not using relative paths? (e.g. if sometimes this is a link and not a filepath that would make sense, but I wasn't aware of any situation when it would be.) The word export is using the absolute filepath, but it's simpler to handle the filepath vs a Uri.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/22)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @aror92)

___
*[`Src/xWorks/LcmWordGenerator.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/22#-NuzDrHHAdkjsSqyWhpF:-NuzDrHHAdkjsSqyWhpG:b2iyqbj) ([raw file](https://github.com/sillsdev/FieldWorks/blob/499f1322f101f799110296d71f8799d61fbf4bd4/Src/xWorks/LcmWordGenerator.cs#L27)):*
> ```Smalltalk
> using A = DocumentFormat.OpenXml.Drawing;
> using DW = DocumentFormat.OpenXml.Drawing.Wordprocessing;
> using PIC = DocumentFormat.OpenXml.Drawing.Pictures;
> ```

More descriptive namespace aliases would be helpful for reading the code. WP for word processing below was tolerable, 
`using Drawing = DocumentFormat.OpenXml.Drawing;`
`using DrawingWP = DocumentFormat.OpenXml.Drawing.Wordprocessing;`
`using Pictures = DocumentFormat.OpenXml.Drawing.Pictures;`

I've never looked into if you can use an alias in a following using which could be nice.
`using Pictures = Drawing.Pictures`

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/22)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @aror92)

___
*[`Src/xWorks/ConfiguredLcmGenerator.cs` line 865 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/22#-NuzDUp62PhAxRWWkuIU:-Nv7_S2L0--iGm1ojXIA:bumspfq) ([raw file](https://github.com/sillsdev/FieldWorks/blob/499f1322f101f799110296d71f8799d61fbf4bd4/Src/xWorks/ConfiguredLcmGenerator.cs#L865)):*
<details><summary><i>Previously, aror92 (Ariel Ror.) wrote…</i></summary><blockquote>

I meant to start a conversation to ask about this here. Is there a reason we want to create a Uri in the case that we're not using relative paths? (e.g. if sometimes this is a link and not a filepath that would make sense, but I wasn't aware of any situation when it would be.) The word export is using the absolute filepath, but it's simpler to handle the filepath vs Uri.ToString, which adds some extra frontmatter.
</blockquote></details>

I believe this is used currently by the preview windows because the xhtml is generated in the temp folder but we don't copy the images there for the preview. If the previews work well without the Uri wrapping then this change is acceptable.
___
*[`Src/xWorks/LcmWordGenerator.cs` line 1353 at r2](https://reviewable.io/reviews/sillsdev/FieldWorks/22#-Nv7_IWj-wyY6XYBAIKf:-Nv7_IWj-wyY6XYBAIKg:b-o5nj5n) ([raw file](https://github.com/sillsdev/FieldWorks/blob/d6376770de75eb66497c9d483ce1a9abe5e408a3/Src/xWorks/LcmWordGenerator.cs#L1353)):*
> ```Smalltalk
> 							{
> 								Id = (UInt32Value)0U,
> 								Name = name + ".jpg"
> ```

Is there a reason for using .jpg here?

**Review by aror92 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/22)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[`Src/xWorks/ConfiguredLcmGenerator.cs` line 865 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/22#-NuzDUp62PhAxRWWkuIU:-Nv8wv0C1pYv5aPV0W6B:b49ga2w) ([raw file](https://github.com/sillsdev/FieldWorks/blob/499f1322f101f799110296d71f8799d61fbf4bd4/Src/xWorks/ConfiguredLcmGenerator.cs#L865)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I believe this is used currently by the preview windows because the xhtml is generated in the temp folder but we don't copy the images there for the preview. If the previews work well without the Uri wrapping then this change is acceptable.
</blockquote></details>

The previews appear unchanged without the Uri wrapping.
___
*[`Src/xWorks/LcmWordGenerator.cs` line 1353 at r2](https://reviewable.io/reviews/sillsdev/FieldWorks/22#-Nv7_IWj-wyY6XYBAIKf:-Nv8x2m419P9mBLj94XB:bue05g3) ([raw file](https://github.com/sillsdev/FieldWorks/blob/d6376770de75eb66497c9d483ce1a9abe5e408a3/Src/xWorks/LcmWordGenerator.cs#L1353)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Is there a reason for using .jpg here?
</blockquote></details>

The image created in the word media file is a jpg (even when the file in FLEx is a png), but there isn't a particular need for the file extension to be in the name, so I've removed it.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/22)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aror92)

___
*[`Src/xWorks/xWorks.csproj` line 171 at r3](https://reviewable.io/reviews/sillsdev/FieldWorks/22#-NvHirTC6hXXjA0ozxLa:-NvHirTC6hXXjA0ozxLb:b-wguqyf) ([raw file](https://github.com/sillsdev/FieldWorks/blob/56b7c739785cf3ed8b4c1776edca8fdd74d7bc92/Src/xWorks/xWorks.csproj#L171)):*
> ```XML
>       <HintPath>..\..\Output\Debug\Newtonsoft.Json.dll</HintPath>
>     </Reference>
>     <Reference Include="PresentationCore" />
> ```

I'm curious about this, I wasn't sure where it was used.

**Review by aror92 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/22)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aror92)

___
*[`Src/xWorks/xWorks.csproj` line 171 at r3](https://reviewable.io/reviews/sillsdev/FieldWorks/22#-NvHirTC6hXXjA0ozxLa:-NvHnA1o7AK4tv08ZSiz:bbo45ab) ([raw file](https://github.com/sillsdev/FieldWorks/blob/56b7c739785cf3ed8b4c1776edca8fdd74d7bc92/Src/xWorks/xWorks.csproj#L171)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I'm curious about this, I wasn't sure where it was used.
</blockquote></details>

It's needed to access the System.Windows.Media.Imaging package, which is used to create the BitmapImage in the Word generator's CreateImage() method.

**Pull request merged**
