### PR TITLE
LT-21708 Add image and caption textframes to word export

### PR DESCRIPTION
**Pull request by aror92**
- Reconfigure images to be inline instead of anchored. (Textframes require inline images; textboxes require anchored.)
- Clean up cloning of image runs.
- Create a global paragraph style to use for textframes.
- Link textframe style to images and their captions and ensure image and associated caption are added to the same textframe.
- Ensure Word does not merge adjacent images into the same textframe. This requires adding an empty paragraph between the image textframes, otherwise Word will automatically merge them into a single textframe that can't be split.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/28)

### CODE REVIEW

**Review by mark-sil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/28)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @aror92)

___
*[`Src/xWorks/LcmWordGenerator.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/28#-NwFahWZ3jJb0PDDDgFg:-NwFahW_7Ieh1xvq_l2C:b-wb3oge) ([raw file](https://github.com/sillsdev/FieldWorks/blob/98443331363e35d07a09738253de4c71486c2640/Src/xWorks/LcmWordGenerator.cs#L6)):*
> ```Smalltalk
> 
> using DocumentFormat.OpenXml;
> using DocumentFormat.OpenXml.Office2010.Drawing;
> ```

Probably remove.



_Code quote:_
```Smalltalk
using DocumentFormat.OpenXml.Office2010.Drawing;
```
___
*[`Src/xWorks/LcmWordGenerator.cs` line 310 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/28#-NwFb6d24nXc-dt7rRVv:-NwFb6d24nXc-dt7rRVw:b-wp1y3b) ([raw file](https://github.com/sillsdev/FieldWorks/blob/98443331363e35d07a09738253de4c71486c2640/Src/xWorks/LcmWordGenerator.cs#L310)):*
> ```Smalltalk
> 				{
> 					WP.ParagraphProperties paragraphProps = new WP.ParagraphProperties(new ParagraphStyleId() { Val = styleName });
> 					par.PrependChild(paragraphProps);
> ```

Nice catch! This fixes some of the problems I was seeing with styles not being applied.



_Code quote:_
```Smalltalk
PrependChild
```
___
*[`Src/xWorks/LcmWordGenerator.cs` line 1008 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/28#-NwFdErLBWkag-uBEDqo:-NwFdErLBWkag-uBEDqp:b-qqq1wc) ([raw file](https://github.com/sillsdev/FieldWorks/blob/98443331363e35d07a09738253de4c71486c2640/Src/xWorks/LcmWordGenerator.cs#L1008)):*
> ```Smalltalk
> 								// and it is being added after another image run was previously added from the same piece,
> 								// we need to append an empty paragraph between to maintain separate textframes.
> 								if (run.Descendants<Drawing>().Any())
> ```

If we only care about adjacent images then instead of Any should we check Last?



_Code quote:_
```Smalltalk
Any
```
___
*[`Src/xWorks/WordStylesGenerator.cs` line 335 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/28#-NwF_hezCnO7A9PrvbXQ:-NwF_hezCnO7A9PrvbXR:b-2eovha) ([raw file](https://github.com/sillsdev/FieldWorks/blob/98443331363e35d07a09738253de4c71486c2640/Src/xWorks/WordStylesGenerator.cs#L335)):*
> ```Smalltalk
> 
> 				case DictionaryNodePictureOptions pictureOptions:
> 					//return new Styles();
> ```

Should this be removed?



_Code quote:_
```Smalltalk
//return new Styles();
```

**Comment by aror92** [comment]
*[`Src/xWorks/LcmWordGenerator.cs` line 1008 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/28#-NwFdErLBWkag-uBEDqo:-NwFkphkBuVaW2CJ20U4:bcziu6v) ([raw file](https://github.com/sillsdev/FieldWorks/blob/98443331363e35d07a09738253de4c71486c2640/Src/xWorks/LcmWordGenerator.cs#L1008)):*
<details><summary><i>Previously, mark-sil (Mark Kidder) wrote…</i></summary><blockquote>

If we only care about adjacent images then instead of Any should we check Last?
</blockquote></details>

This line only functions to verify that the current run contains an image. (Any is preferable to last for that check because the image run could contain e.g. a text object after the image, but if an image is contained anywhere inside the run, the run is an "image run".)

We could add a check for if the image runs in question are adjacent. But, looking for adjacent images won't have the expected result because each image run is followed by other runs containing associated items like Caption, Copyright & License that are added to the textframe but do not contain images. 

My understanding is that a piece corresponds to one lexical entry, and the images are all added sequentially at the end of the piece, after all of the senses. So the order of runs within a piece is: headword run, sense1 run, sense2 run, ... , [image1 run, caption1 run, copyright&license1 run], [image2 run, caption2 run, copyright&license2 run]... In other words, if a piece contains more than one image, they will all be adjacent. Since we need empty paragraphs added between the [] textframe chunks, this corresponds to adding an empty paragraph immediately before any image run that is not the first image run.

**Review by mark-sil — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/28#-:-NwFtjEKE9dASJSxrPJi:bnfp4nl)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @aror92)

**Review by aror92 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/28)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @mark-sil)

___
*[`Src/xWorks/LcmWordGenerator.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/28#-NwFahWZ3jJb0PDDDgFg:-NwFsCem2zLqTCCiscU_:b-896fix) ([raw file](https://github.com/sillsdev/FieldWorks/blob/98443331363e35d07a09738253de4c71486c2640/Src/xWorks/LcmWordGenerator.cs#L6)):*
<details><summary><i>Previously, mark-sil (Mark Kidder) wrote…</i></summary><blockquote>

Probably remove.
</blockquote></details>

Done.
___
*[`Src/xWorks/LcmWordGenerator.cs` line 310 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/28#-NwFb6d24nXc-dt7rRVv:-NwFsILrAR0n6kjJ9awe:boyexb3) ([raw file](https://github.com/sillsdev/FieldWorks/blob/98443331363e35d07a09738253de4c71486c2640/Src/xWorks/LcmWordGenerator.cs#L310)):*
<details><summary><i>Previously, mark-sil (Mark Kidder) wrote…</i></summary><blockquote>

Nice catch! This fixes some of the problems I was seeing with styles not being applied.
</blockquote></details>

Done. Thanks!
___
*[`Src/xWorks/WordStylesGenerator.cs` line 335 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/28#-NwF_hezCnO7A9PrvbXQ:-NwFsAfNC83tRzdrkWd-:b-896fix) ([raw file](https://github.com/sillsdev/FieldWorks/blob/98443331363e35d07a09738253de4c71486c2640/Src/xWorks/WordStylesGenerator.cs#L335)):*
<details><summary><i>Previously, mark-sil (Mark Kidder) wrote…</i></summary><blockquote>

Should this be removed?
</blockquote></details>

Done.

**Review by mark-sil — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/28)* status: all files reviewed, 2 unresolved discussions (waiting on @aror92)

**Review by mark-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aror92)

**Review by mark-sil — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aror92)

**Pull request merged**
