### PR TITLE
LT 21756: Add testbed capabilities for the parsers

### PR DESCRIPTION
**Pull request by jtmaxwell3**
This is a new feature that parses a user-specified set of sentences are reports the results.  The results are stored in a directory, and can be compared over time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/102)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`Src/LexText/ParserCore/ParserReport.cs` line 132 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1Sj_MgAjUaYkcp5xHV:-O1Sj_MgAjUaYkcp5xHW:b-2mlbex) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserReport.cs#L132)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="word"></param>
> 		/// <param name="report"></param>
> ```

If all of the parameters are self explanatory I prefer to leave these lines off the summary. (the IDE will complain if you have some but not if you have none. For future reference if you have some that need explanation the ones without a description can use a self-closing tag. e.g. <param name="report" />

**Comment by jasonleenaylor** [comment]
*[`Src/LexText/ParserCore/ParserReport.cs` line 153 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1Sk6s7AeAYLZK7cPW0:-O1Sk6s7AeAYLZK7cPW1:b8qfwq7) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserReport.cs#L153)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="filename"></param>
> 		/// <returns></returns>
> ```

Remove empty param and returns throughout the file.



_Code quote:_
```Smalltalk
		/// <param name="filename"></param>
		/// <returns></returns>
```

**Comment by jasonleenaylor** [comment]
*[`Src/LexText/ParserCore/ParserReport.cs` line 211 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1SkPF_3LE4yJRZZjzm:-O1SkPF_3LE4yJRZZjzn:b-nu7uzb) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserReport.cs#L211)):*
> ```Smalltalk
> 		public static string GetProjectReportsDirectory(LcmCache cache)
> 		{
> 			// TODO: Handle the case when the project isn't local.
> ```

How would that matter here?



_Code quote:_
```Smalltalk
// TODO: Handle the case when the project isn't local.
```

**Comment by jtmaxwell3** [comment]
I heard somewhere that projects that are passed around using Send/Receive are formatted differently, and I was worried that there wouldn't be a directory to read or write to, so I added a TODO comment for this case.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/102)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jtmaxwell3)

___
*[`Src/LexText/ParserCore/ParserReport.cs` line 172 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1Sop9k-bTVxLoNKXQ9:-O1Sop9k-bTVxLoNKXQA:bh0mc69) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserReport.cs#L172)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="filename"></param>
> 		public void WriteJsonFile(string filename)
> ```

private?



_Code quote:_
```Smalltalk
public
```
___
*[`Src/LexText/ParserCore/ParserReport.cs` line 223 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1SkbmE0tBJCh_MNZr0:-O1SkbmF5NPYGF4_uK0s:b-wd8o0b) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserReport.cs#L223)):*
> ```Smalltalk
> 		/// <param name="report2"></param>
> 		/// <returns></returns>
> 		public ParserReport DiffParserReports (ParserReport report2)
> ```

stray whitespace.
___
*[`Src/LexText/ParserCore/ParserReport.cs` line 223 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1SkjYACDgbYN3y5SXH:-O1SkjYACDgbYN3y5SXI:bjpuyov) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserReport.cs#L223)):*
> ```Smalltalk
> 		/// <param name="report2"></param>
> 		/// <returns></returns>
> 		public ParserReport DiffParserReports (ParserReport report2)
> ```

I would prefer 'other 'as a name



_Code quote:_
```Smalltalk
report2
```
___
*[`Src/LexText/ParserCore/ParserReport.cs` line 266 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1Sl00F-9mzO4a0xm8G:-O1Sl00F-9mzO4a0xm8H:b-ca5pvt) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserReport.cs#L266)):*
> ```Smalltalk
> 		}
> 
> 		string DiffNames(string name1, string name2)
> ```

name, otherName



_Code quote:_
```Smalltalk
name1, string name2
```
___
*[`Src/LexText/ParserCore/ParserReport.cs` line 321 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1SlKTu5-n7Xr4H_Lle:-O1SlKTu5-n7Xr4H_Llf:bhmp65i) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserReport.cs#L321)):*
> ```Smalltalk
> 
> 			foreach (string key in ParseReports.Keys)
> 				if (!ParseReports[key].Equals(other.ParseReports[key])) return false;
> ```

I think it is theoretically impossible for any of the checks after Timestamp to run... I suppose it doesn't hurt to leave them.
Also you could have a:
return SourceText == other.SourceText && NumWords == other.NumWords... if we could at least assume that a user could not create two non-identical ParserReports on the same system at the same time with different ParseReports contents.
___
*[`Src/LexText/ParserCore/ParserWorker.cs` line 188 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1Sn4KR-gH4MC5muEXK:-O1Sn4KR-gH4MC5muEXL:b-fd2fvh) ([raw file](https://github.com/sillsdev/FieldWorks/blob/e0fdca0de68add2a7af227986a058e5140364cef/Src/LexText/ParserCore/ParserWorker.cs#L188)):*
> ```Smalltalk
> 			}
> 
> 			if (wordformHash == result.GetHashCode())
> ```

What was this doing before?
___
*[`Src/LexText/ParserCore/ParserCoreTests/ParserReportTests.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1SpY9C7eNb5F4IML0Z:-O1SpY9C7eNb5F4IML0_:b53socy) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserCoreTests/ParserReportTests.cs#L63)):*
> ```Smalltalk
> 			Assert.AreEqual(numNoOpinion, report.NumUserNoOpinionAnalyses);
> 			Assert.AreEqual(parseTime, report.ParseTime);
> 			Assert.AreEqual(errorMessage, report.ErrorMessage);
> ```

        Assert.That(report.NumAnalyses, Is.EqualTo(numAnalyses));
        Assert.That(report.NumUserDisapprovedAnalyses, Is.EqualTo(numDisapproved));
        Assert.That(report.NumUserApprovedAnalysesMissing, Is.EqualTo(numApprovedMissing));
        Assert.That(report.NumUserNoOpinionAnalyses, Is.EqualTo(numNoOpinion));
        Assert.That(report.ParseTime, Is.EqualTo(parseTime));
        Assert.That(report.ErrorMessage, Is.EqualTo(errorMessage));



_Code quote:_
```Smalltalk
			Assert.AreEqual(numAnalyses, report.NumAnalyses);
			Assert.AreEqual(numDisapproved, report.NumUserDisapprovedAnalyses);
			Assert.AreEqual(numApprovedMissing, report.NumUserApprovedAnalysesMissing);
			Assert.AreEqual(numNoOpinion, report.NumUserNoOpinionAnalyses);
			Assert.AreEqual(parseTime, report.ParseTime);
			Assert.AreEqual(errorMessage, report.ErrorMessage);
```
___
*[`Src/LexText/ParserCore/ParserCoreTests/ParserReportTests.cs` line 77 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1SpzdfARRq2X3aFblR:-O1SpzdfARRq2X3aFblS:b4gv5ha) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserCoreTests/ParserReportTests.cs#L77)):*
> ```Smalltalk
> 			Assert.AreEqual(numWords, report.NumWords);
> 			Assert.AreEqual(numZeroParses, report.NumZeroParses);
> 			Assert.AreEqual(totalParseTime, report.TotalParseTime);
> ```

Assert.That(report.TotalAnalyses, Is.EqualTo(totalAnalyses));
Assert.That(report.TotalUserDisapprovedAnalyses, Is.EqualTo(totalDisapproved));
Assert.That(report.TotalUserApprovedAnalysesMissing, Is.EqualTo(totalApprovedMissing));
Assert.That(report.TotalUserNoOpinionAnalyses, Is.EqualTo(totalNoOpinion));
Assert.That(report.NumParseErrors, Is.EqualTo(numParseErrors));
Assert.That(report.NumWords, Is.EqualTo(numWords));
Assert.That(report.NumZeroParses, Is.EqualTo(numZeroParses));
Assert.That(report.TotalParseTime, Is.EqualTo(totalParseTime));



_Code quote:_
```Smalltalk
			Assert.AreEqual(totalAnalyses, report.TotalAnalyses);
			Assert.AreEqual(totalDisapproved, report.TotalUserDisapprovedAnalyses);
			Assert.AreEqual(totalApprovedMissing, report.TotalUserApprovedAnalysesMissing);
			Assert.AreEqual(totalNoOpinion, report.TotalUserNoOpinionAnalyses);
			Assert.AreEqual(numParseErrors, report.NumParseErrors);
			Assert.AreEqual(numWords, report.NumWords);
			Assert.AreEqual(numZeroParses, report.NumZeroParses);
			Assert.AreEqual(totalParseTime, report.TotalParseTime);
```
___
*[`Src/LexText/ParserCore/ParserCoreTests/ParserReportTests.cs` line 252 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1SqKC36tKYD1ntEgo1:-O1SqKC36tKYD1ntEgo2:b-v6qbr8) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserCoreTests/ParserReportTests.cs#L252)):*
> ```Smalltalk
> 			string filename = parserReport.WriteJsonFile(Cache);
> 			var jsonParserReport = ParserReport.ReadJsonFile(filename);
> 			Assert.AreEqual(parserReport, jsonParserReport);
> ```

var diff = parserReport2.DiffParserReports(parserReport);
Assert.That(diff.ParseReports.ContainsKey("extra"), Is.True);
CheckParseReport(diff.ParseReports["extra"], parseTime: 2, errorMessage: "missing => ");
Assert.That(diff.ParseReports.ContainsKey("zero"), Is.True);
CheckParseReport(diff.ParseReports["zero"], parseTime: -2, errorMessage: " => missing");
Assert.That(diff.ParseReports.ContainsKey("cat"), Is.True);
CheckParseReport(diff.ParseReports["cat"]);

// Check json.
// Verify that character encoding is preserved.
parserReport.AddParseReport("español", zeroReport);
string filename = parserReport.WriteJsonFile(Cache);
var jsonParserReport = ParserReport.ReadJsonFile(filename);
Assert.That(parserReport, Is.EqualTo(jsonParserReport));

although the second argument in the fluent style assert is the expected value, so maybe the last assert should have the arguments flipped.



_Code quote:_
```Smalltalk
			var diff = parserReport2.DiffParserReports(parserReport);
			Assert.IsTrue(diff.ParseReports.ContainsKey("extra"));
			CheckParseReport(diff.ParseReports["extra"], parseTime: 2, errorMessage: "missing => ");
			Assert.IsTrue(diff.ParseReports.ContainsKey("zero"));
			CheckParseReport(diff.ParseReports["zero"], parseTime: -2, errorMessage: " => missing");
			Assert.IsTrue(diff.ParseReports.ContainsKey("cat"));
			CheckParseReport(diff.ParseReports["cat"]);

			// Check json.
			// Verify that character encoding is preserved.
			parserReport.AddParseReport("español", zeroReport);
			string filename = parserReport.WriteJsonFile(Cache);
			var jsonParserReport = ParserReport.ReadJsonFile(filename);
			Assert.AreEqual(parserReport, jsonParserReport);
```
___
*[`Src/LexText/ParserCore/ParserCoreTests/ParseWorkerTests.cs` line 164 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1SnfF92KuBToRTe8dm:-O1SnfF92KuBToRTe8dn:b2i9rnk) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserCore/ParserCoreTests/ParseWorkerTests.cs#L164)):*
> ```Smalltalk
> 			bVal = parserWorker.UpdateWordform(catsLowerTest, ParserPriority.Low);
> 			ExecuteIdleQueue();
> 			Assert.IsTrue(bVal);
> ```

I assume this is a result of the hash comparison change I was curious about in the other file.
___
*[`Src/LexText/ParserUI/ParserListener.cs` line 529 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1Sqn-i8qvgNvalQu4l:-O1Sqn-j9XplHMo01yHw:b-tqp06m) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserUI/ParserListener.cs#L529)):*
> ```Smalltalk
> 					if (text is IStText iStText)
> 						foreach (var genre in iStText.GenreCategories)
> 							if (genre.ShortName == "Testbed")
> ```

I want to make this a const somewhere...hmm, strike that, the genre name can be translated. We need to key off an id. Also that means we should include the genre in the Template file which I think lives in LCM. We can keep this for now and fix that in a follow up commit so we can ship this in our patch.
___
*[`Src/LexText/ParserUI/ParserReportDialog.xaml` line 30 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1St2abB1luqQYmOrO3:-O1St2abB1luqQYmOrO4:bd52g5h) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserUI/ParserReportDialog.xaml#L30)):*
> ```XML
> 							<Label ToolTip="the word that was parsed">Word</Label>
> 							<Separator/>
> 							<Label ToolTip ="number of words"
> ```

I think initial cap on all the tooltips is best



_Code quote:_
```XML
n
```
___
*[`Src/LexText/ParserUI/ParserReportsDialog.xaml` line 61 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1StG4uAPRV9ndUiMee:-O1StG4uAPRV9ndUiMef:b-9n59kk) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserUI/ParserReportsDialog.xaml#L61)):*
> ```XML
> 				<DataGridTextColumn Binding="{Binding SourceText}">
> 					<DataGridTextColumn.Header>
> 						<Label ToolTip="the text that was parsed">Text</Label>
> ```

Init caps throughout this file on tooltips



_Code quote:_
```XML
t
```
___
*[`Src/LexText/ParserUI/ParserReportsViewModel.cs` line 44 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1St_4yC4yqKlfEFLR5:-O1St_4yC4yqKlfEFLR6:b-rf9o95) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserUI/ParserReportsViewModel.cs#L44)):*
> ```Smalltalk
> 			else
> 			{
> 				// Runtime data loading logic here
> ```

I think you put this logic elsewhere, so we can remove this else
___
*[`Src/LexText/ParserUI/TryAWordDlg.cs` line 181 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-O1Su8-BAkZP5iMCupVo:-O1Su8-BAkZP5iMCupVp:b-e8srze) ([raw file](https://github.com/sillsdev/FieldWorks/blob/474b4ffcbc7177beea7a730eac5a0fd6a70c997d/Src/LexText/ParserUI/TryAWordDlg.cs#L181)):*
> ```Smalltalk
> 		}
> 
> 		public void SetWordToUse(string word)
> ```

is this needed after the change to the constructor?



_Code quote:_
```Smalltalk
public 
```

**Comment by jtmaxwell3** [comment]
I fixed everything except for the following:
- ParserReport.Equal is used for testing purposes, so it checks everything.
- I couldn't find "if (wordformHash == result.GetHashCode())" in ParserWorker.  What version were you looking at?
- I didn't change Assert.Equal to Assert.That because it was too big a change and I was worried that I would fat finger something.
- I think you are right about the change to ParserWorkerTests, but it has been a while.
- SetWordToUse is public so it can be used by ParserListener.TryAWord so that TryThisWord can override the word used.

**Comment by jasonleenaylor** [comment]
I'd like a bit more research on the hashcode change, but other than that I agree with your non-change, or delayed-change requests.

**Comment by jtmaxwell3** [comment]
I looked at the hashcode change.  The code "if (wordformHash == result.GetHashCode()) return false;" was just a performance optimization to avoid calling m_parseFiler.ProcessParse if nothing changed.  However, I wanted ProcessParse to always be called so that I would know when all of the words had been parsed (even those that didn't change).  I moved the check inside of ProcessParse so that it could still avoid redisplaying words that hadn't changed.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-:-O1TXMEI-IATlF6OR3Ny:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jtmaxwell3)

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/102#-:-O1XeoV63FDSmF3pdLGz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jtmaxwell3)

**Pull request merged**
