### PR TITLE
LT-21786: Show variant info for analysis chooser

### PR DESCRIPTION
**Pull request by JakeOliver28**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/72)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`Src/LexText/Interlinear/ChooseAnalysisHandler.cs` line 378 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/72#-NzEObda2MyIGLYslZHz:-NzEObda2MyIGLYslZI-:bm2divy) ([raw file](https://github.com/sillsdev/FieldWorks/blob/f39542f05a0c6e51a7ed7d2769f30071c746a5b3/Src/LexText/Interlinear/ChooseAnalysisHandler.cs#L378)):*
> ```Smalltalk
> 			ITsStrBldr tsb = TsStringUtils.MakeStrBldr();
> 			ISilDataAccess sda = fdoCache.MainCacheAccessor;
> 			ILexEntry entry = null;
> ```

I don't think this change was necessary.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/72)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JakeOliver28)

**Review by JakeOliver28 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/72)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[`Src/LexText/Interlinear/ChooseAnalysisHandler.cs` line 378 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/72#-NzEObda2MyIGLYslZHz:-NzEhyt7EPQDl1XC3lEF:b-8o67cl) ([raw file](https://github.com/sillsdev/FieldWorks/blob/f39542f05a0c6e51a7ed7d2769f30071c746a5b3/Src/LexText/Interlinear/ChooseAnalysisHandler.cs#L378)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I don't think this change was necessary.
</blockquote></details>

Got rid of the unnecessary changes here.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/72)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JakeOliver28)

**Pull request merged**
