### PR TITLE
Word Export: Fix paragraph style problems

### PR DESCRIPTION
**Pull request by mark-sil**
Fix missing styles.
Fix incorrect basedOn style names.
Continuation styles are now based on other continuation styles. Add code to set the RTL flag. (use will be in a separate submission.) For the ‘Normal’ style set the default font name and font size.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/138)

### CODE REVIEW

**Review by aror92 — COMMENTED** [review]
Have a few files to review still, but this is looking great. Nice handling of the based on hierarchy. I have one question in the new AddBasedOnStyle method

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/138#-:-O4L-Ri6E5_9qLbh2jGP:b-h5frqm)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @mark-sil)

___
*[`Src/xWorks/LcmWordGenerator.cs` line 1690 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/138#-O4KxTGlCSLkVLbTh1h_:-O4KxTGlCSLkVLbTh1ha:b1odzd8) ([raw file](https://github.com/sillsdev/FieldWorks/blob/711f1f7d08c0181968168c14495f301d9badca1c/Src/xWorks/LcmWordGenerator.cs#L1690)):*
> ```Smalltalk
> 					{
> 						basedOnStyle = WordStylesGenerator.GenerateWordStyleFromLcmStyleSheet(style.BasedOn.Val, 0, node, propertyTable, !continuationStyle);
> 						bool basedOnIsDifferent = basedOnStyle.BasedOn?.Val != null && basedOnStyle.StyleId != basedOnStyle.BasedOn?.Val;
> ```

I think I'm missing something about the second part of this check. The first part of the check looks at whether the based on style is itself based on a style. But it seems like the second part is checking that the style is not based on itself--why is that needed?

**Review by mark-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/138)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @aror92)

___
*[`Src/xWorks/LcmWordGenerator.cs` line 1690 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/138#-O4KxTGlCSLkVLbTh1h_:-O4LExyeD9YlaM0skS6H:bs78x0k) ([raw file](https://github.com/sillsdev/FieldWorks/blob/711f1f7d08c0181968168c14495f301d9badca1c/Src/xWorks/LcmWordGenerator.cs#L1690)):*
<details><summary><i>Previously, aror92 (Ariel Ror.) wrote…</i></summary><blockquote>

I think I'm missing something about the second part of this check. The first part of the check looks at whether the based on style is itself based on a style. But it seems like the second part is checking that the style is not based on itself--why is that needed?
</blockquote></details>

Yes, you are correct in what it is doing.  Sometimes we get a style that is based on itself.  It happens when a style does not have a basedOn style in FLEX, so we always see it for the "Normal" style, and it could possibly happen for others. LCM has code that specifically adds this (lines 81 and 82 in BaseStyleInfo.cs):
 if (string.IsNullOrEmpty(this.m_basedOnStyleName))
   this.m_basedOnStyleName = copyFrom.Name;
I have no idea why LCM is doing this, but I don't want to change it.  

I'll add a comment to our code.

**Review by aror92 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/138#-:-O4MWEQw4M3Dk2ZCtEAk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mark-sil)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/138)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mark-sil)

**Pull request merged**
