### PR TITLE
Add menu items for moving fields up and down in the interface

### PR DESCRIPTION
**Pull request by jasonleenaylor**
* Add menu items and first cut at handlers for it
* Also cleaned up some obsolete code

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/127)

### CODE REVIEW

**Review by aror92 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/127)* status: all files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[`Src/Common/Controls/DetailControls/Slice.cs` line 2804 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/127#-O5FijnJ5n10CoBHI_3r:-O5FijnK194eA7_4ov-Y:bbk5uo6) ([raw file](https://github.com/sillsdev/FieldWorks/blob/c24430b55fafd608ba40b4acf470a7bd568a8f2f/Src/Common/Controls/DetailControls/Slice.cs#L2804)):*
> ```Smalltalk
> 						continue;
> 					}
> 					else
> ```

Do we expect only one node to enter this else statement? Or are we aiming to find the last node that enters this else statement--and in that case, why do we know that last node is the one to use for fieldRef?
___
*[`Src/Common/Controls/DetailControls/Slice.cs` line 3028 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/127#-O5Fllr0CgnrzLR2vLhR:-O5Fllr0CgnrzLR2vLhS:b-f5cm6o) ([raw file](https://github.com/sillsdev/FieldWorks/blob/c24430b55fafd608ba40b4acf470a7bd568a8f2f/Src/Common/Controls/DetailControls/Slice.cs#L3028)):*
> ```Smalltalk
> 			display.Enabled = ContainingDataTree.ShowingAllFields && CheckValidMove(display, Direction.Up);
> 
> 			return true;
> ```

Why is it that OnDisplayMoveField[Up/Down] and OnMoveField[Up/Down] always return true? (Instead of e.g. returning the value of display.Enabled)

**Comment by jasonleenaylor** [comment]
*[`Src/Common/Controls/DetailControls/Slice.cs` line 2804 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/127#-O5FijnJ5n10CoBHI_3r:-O5JHmUk9pvQHlw9tmLu:b-si8drf) ([raw file](https://github.com/sillsdev/FieldWorks/blob/c24430b55fafd608ba40b4acf470a7bd568a8f2f/Src/Common/Controls/DetailControls/Slice.cs#L2804)):*
<details><summary><i>Previously, aror92 (Ariel Ror.) wrote…</i></summary><blockquote>

Do we expect only one node to enter this else statement? Or are we aiming to find the last node that enters this else statement--and in that case, why do we know that last node is the one to use for fieldRef?
</blockquote></details>

Oops, all of this was just for debugging. I should clean this out.

**Comment by jasonleenaylor** [comment]
*[`Src/Common/Controls/DetailControls/Slice.cs` line 3028 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/127#-O5Fllr0CgnrzLR2vLhR:-O5JISpsBMnRiULAPJ5e:b-cg92z7) ([raw file](https://github.com/sillsdev/FieldWorks/blob/c24430b55fafd608ba40b4acf470a7bd568a8f2f/Src/Common/Controls/DetailControls/Slice.cs#L3028)):*
<details><summary><i>Previously, aror92 (Ariel Ror.) wrote…</i></summary><blockquote>

Why is it that OnDisplayMoveField[Up/Down] and OnMoveField[Up/Down] always return true? (Instead of e.g. returning the value of display.Enabled)
</blockquote></details>

Returning true indicates that the message was handled. The user experience is controlled through the 'display' variable.

**Review by aror92 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/127#-:-O5JrWoqBVOrZd1x--Vf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Pull request merged**
