### PR TITLE
Implement Lt 21911: Novel Root Guesser

### PR DESCRIPTION
**Pull request by jtmaxwell3**
This implements the Fieldworks side of https://jira.sil.org/browse/LT-21911.  It uses HermitCrab 3.3.0.  It changes the FieldWorks display code to show the underlying form of a morph bundle instead of the morpheme's lexeme when the lexeme is a lexical pattern.  Normally, the underlying form and the lexeme are the same (except perhaps for canonicalization), but in this case they are quite different.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/172)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`Src/LexText/ParserCore/HCLoader.cs` line 2237 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/172#-O8hAYcS3oVaMplSQyNV:-O8hAYcS3oVaMplSQyNW:b38srg2) ([raw file](https://github.com/sillsdev/FieldWorks/blob/c08f0d57bce82577cb222b46ce4132512f556ef1/Src/LexText/ParserCore/HCLoader.cs#L2237)):*
> ```Smalltalk
> 			// This assumes that "[" and "]" are not part of any phonemes.
> 			return form.Contains("[") && form.Contains("]");
> 		}
> ```

I would like to have a single IsLexicalPattern if the current project dependencies allow us. This way if we change our criteria we only have to do it in one place.



_Code quote:_
```Smalltalk
		/// <summary>
		/// Does form contain a lexical pattern (e.g. [Seg]*)?
		/// </summary>
		public static bool IsLexicalPattern(string form)
		{
			// This assumes that "[" and "]" are not part of any phonemes.
			return form.Contains("[") && form.Contains("]");
		}
```

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/172)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jtmaxwell3)

___
*[`Src/LexText/ParserCore/ParseResult.cs` line 166 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/172#-O8hBxPg0cR9WpTaoHy-:-O8hBxPg0cR9WpTaoHy0:bvhgzzf) ([raw file](https://github.com/sillsdev/FieldWorks/blob/c08f0d57bce82577cb222b46ce4132512f556ef1/Src/LexText/ParserCore/ParseResult.cs#L166)):*
> ```Smalltalk
> 		}
> 
> 		public ParseMorph(IMoForm form, IMoMorphSynAnalysis msa, ILexEntryInflType inflType)
> ```

Since you added a new constructor with one extra parameter could you change this to follow the pattern used in the constructor defined above?
___
*[`Src/LexText/ParserCore/ParserCore.csproj` line 175 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/172#-O8hCF-kBIEo-nD31xU_:-O8hCF-kBIEo-nD31xUa:b-2bm1yb) ([raw file](https://github.com/sillsdev/FieldWorks/blob/c08f0d57bce82577cb222b46ce4132512f556ef1/Src/LexText/ParserCore/ParserCore.csproj#L175)):*
> ```XML
>       <HintPath>..\..\..\Output\Debug\ApplicationTransforms.dll</HintPath>
>     </Reference>
>     <Reference Include="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" />
> ```

I didn't see what made this necessary.
___
*[`Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs` line 965 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/172#-O8hCW8I7cebz075b1ky:-O8hCW8I7cebz075b1kz:b-eolezg) ([raw file](https://github.com/sillsdev/FieldWorks/blob/c08f0d57bce82577cb222b46ce4132512f556ef1/Src/LexText/ParserCore/ParserCoreTests/HCLoaderTests.cs#L965)):*
> ```Smalltalk
> 			AllomorphCoOccurrenceRule coOccurRule = hcStemEntry.PrimaryAllomorph.AllomorphCoOccurrenceRules.First();
> 			Assert.That(coOccurRule.Adjacency, Is.EqualTo(MorphCoOccurrenceAdjacency.SomewhereToRight));
> 			Assert.That(coOccurRule.Others.Select(a => a.Morpheme.ToString()), Is.EqualTo(new[] {"-ɯd"}));
> ```


These old asserts may no longer be valid, but I'd like to see some new ones.
Can we add a new test or some new asserts to validate the new logic?

**Comment by jtmaxwell3** [comment]
I couldn't find a file to put IsLexicalRelation in that was accessible to both SandboxBase and HCLoader.

coOccurRule.Key doesn't exist in HermitCrab anymore because of a change to HermitCrab unrelated to my change.  I implemented unit tests for the novel root guesser in the HermitCrab library.  Most of the changes in FieldWorks are related to the UI and are covered by the acceptance test.  Did you have a specific unit test in mind?

I fixed the other two issues.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/172#-:-O8hxMnI-D-4tDlSJjDq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jtmaxwell3)

**Pull request merged**
