### PR TITLE
Word Export: Fix multiple root names that are the same

### PR DESCRIPTION
**Pull request by mark-sil**
When building a style that is based on another style, make sure we are not creating a new style with a root that is the same as the root of the basedOn style.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/88)

### CODE REVIEW

**Review by JakeOliver28 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/88)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mark-sil)

___
*[`Src/xWorks/LcmWordGenerator.cs` line 1780 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/88#-O-q0yizEOTf8qY_fECG:-O-q0yizEOTf8qY_fECH:bs9ufdk) ([raw file](https://github.com/sillsdev/FieldWorks/blob/031dafc861f6379c79ee49579c059f45ca685b34/Src/xWorks/LcmWordGenerator.cs#L1780)):*
> ```Smalltalk
> 							{
> 								// Don't create a new style if the current style already has the same root.
> 								int compareTo = currentRunStyle.IndexOf(WordStylesGenerator.StyleSeparator);
> ```

Could we rename compareTo? Its name feels a little nebulous to me. Maybe separatorIndex?
___
*[`Src/xWorks/LcmWordGenerator.cs` line 1783 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/88#-O-q18mr91NHXg3OFJsI:-O-q18mr91NHXg3OFJsJ:b-mduumn) ([raw file](https://github.com/sillsdev/FieldWorks/blob/031dafc861f6379c79ee49579c059f45ca685b34/Src/xWorks/LcmWordGenerator.cs#L1783)):*
> ```Smalltalk
> 								compareTo = compareTo != -1 ? compareTo : currentRunStyle.IndexOf("[");
> 								if ((compareTo == -1 && currentRunStyle.Equals(styleDisplayName)) ||
> 									(compareTo != -1 && currentRunStyle.Substring(0, compareTo).Equals(styleDisplayName)))
> ```

Could we simplify this/improve readability with a ternary operator? 

bool hasSameRoot = compareTo == -1 ? currentRunStyle.Equals(styleDisplayName) : currentRunStyle.Substring(0, compareTo).Equals(styleDisplayName)

if (hasSameRoot)
{
	return;
}

**Review by mark-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/88)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @JakeOliver28)

___
*[`Src/xWorks/LcmWordGenerator.cs` line 1780 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/88#-O-q0yizEOTf8qY_fECG:-O-qLqzp9X22OjUe8_q-:b-ciluov) ([raw file](https://github.com/sillsdev/FieldWorks/blob/031dafc861f6379c79ee49579c059f45ca685b34/Src/xWorks/LcmWordGenerator.cs#L1780)):*
<details><summary><i>Previously, JakeOliver28 (Jake Oliver) wrote…</i></summary><blockquote>

Could we rename compareTo? Its name feels a little nebulous to me. Maybe separatorIndex?
</blockquote></details>

Yes. Thanks for the improvement.
___
*[`Src/xWorks/LcmWordGenerator.cs` line 1783 at r1](https://reviewable.io/reviews/sillsdev/FieldWorks/88#-O-q18mr91NHXg3OFJsI:-O-qLzYR4ZAOzMpVJE38:b-ciluov) ([raw file](https://github.com/sillsdev/FieldWorks/blob/031dafc861f6379c79ee49579c059f45ca685b34/Src/xWorks/LcmWordGenerator.cs#L1783)):*
<details><summary><i>Previously, JakeOliver28 (Jake Oliver) wrote…</i></summary><blockquote>

Could we simplify this/improve readability with a ternary operator? 

bool hasSameRoot = compareTo == -1 ? currentRunStyle.Equals(styleDisplayName) : currentRunStyle.Substring(0, compareTo).Equals(styleDisplayName)

if (hasSameRoot)
{
	return;
}
</blockquote></details>

Yes. Thanks for the improvement.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/88)* status: all files reviewed, 2 unresolved discussions (waiting on @JakeOliver28)

**Review by JakeOliver28 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/FieldWorks/88#-:-O-wgZPT4DpKbXYORJuc:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mark-sil)

**Pull request merged**
